[package]
name = "ru-rs"
version = "0.1.0"
authors = ["alex"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serial = "0.4"

[[example]]
name= "fx"
path= "example/fx.rs"