//! SeaORM Entity. Generated by sea-orm-codegen 0.9.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "customs_org")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub school: Option<String>,
    pub group: Option<String>,
    pub addr: Option<String>,
    pub group_id: Option<i32>,
    pub created_at: DateTimeUtc,
    pub update_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::customs::Entity")]
    Customs,
}

impl Related<super::customs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
