//! SeaORM Entity. Generated by sea-orm-codegen 0.9.1

pub mod prelude;

pub mod customs;
pub mod customs_org;
pub mod goods_info;
pub mod order;
pub mod production;
pub mod role;
pub mod sea_orm_active_enums;
pub mod user;
