//! SeaORM Entity. Generated by sea-orm-codegen 0.9.1

pub use super::customs::Entity as Customs;
pub use super::customs_org::Entity as CustomsOrg;
pub use super::goods_info::Entity as GoodsInfo;
pub use super::order::Entity as Order;
pub use super::production::Entity as Production;
pub use super::role::Entity as Role;
pub use super::user::Entity as User;
