//! SeaORM Entity. Generated by sea-orm-codegen 0.9.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "production")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub serial_num: String,
    pub cas: String,
    pub inventory: String,
    pub brand: String,
    pub category: Option<String>,
    pub pro_category: Option<String>,
    pub name_zh: String,
    pub name_en: String,
    pub size: Option<String>,
    pub price: Option<f32>,
    pub amount: i64,
    pub created_at: DateTimeUtc,
    pub update_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::order::Entity")]
    Order,
}

impl Related<super::order::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Order.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
